In [167]:
import numpy as np

In [168]:
# Ovde su sve tacke cije su koordinate procitane sa slike.

# left
x1 = np.array([332, 74, 1])
x2 = np.array([500, 54, 1])
x3 = np.array([717, 165, 1])
x4 = np.array([537, 188, 1])
x5 = np.array([328, 293, 1])
x6 = np.array([])
x7 = np.array([713, 402, 1])
x8 = np.array([537, 429, 1])
x9 = np.array([259, 339, 1])
x10 = np.array([])
x11 = np.array([773, 365, 1])
x12 = np.array([311, 408, 1])
x13 = np.array([266, 591, 1])
x14 = np.array([])
x15 = np.array([768, 615, 1])
x16 = np.array([313, 671, 1])
x17 = np.array([91, 629, 1])
x18 = np.array([])
x19 = np.array([925, 599, 1])
x20 = np.array([699, 782, 1])
x21 = np.array([93, 824, 1])
x22 = np.array([])
x23 = np.array([918, 788, 1])
x24 = np.array([695, 987, 1])

# right
y1 = np.array([392, 75, 1])
y2 = np.array([563, 73, 1])
y3 = np.array([566, 197, 1])
y4 = np.array([370, 198, 1])
y5 = np.array([])
y6 = np.array([])
y7 = np.array([567, 424, 1])
y8 = np.array([375, 424, 1])
y9 = np.array([280, 312, 1])
y10 = np.array([714, 331, 1])
y11 = np.array([686, 401, 1])
y12 = np.array([234, 378, 1])
y13 = np.array([])
y14 = np.array([716, 555, 1])
y15 = np.array([685, 641, 1])
y16 = np.array([245, 615, 1])
y17 = np.array([121, 549, 1])
y18 = np.array([])
y19 = np.array([861, 652, 1])
y20 = np.array([458, 779, 1])
y21 = np.array([127, 721, 1])
y22 = np.array([])
y23 = np.array([858, 837, 1])
y24 = np.array([461, 976, 1])

In [169]:
# Odredjivanje nedostajucih tacaka.

def cross(x, y):
    z = np.cross(x, y)
    return z * (1/z[2])

# teeakane
# left
x6 = cross(cross(cross(cross(x4, x1), cross(x3, x2)), x7), 
           cross(cross(cross(x8, x4), cross(x7, x3)), x2))
x6 = np.round(x6 * (1/x6[2]))
print('x6:', x6)
# right
y6 = cross(cross(cross(cross(y4, y1), cross(y3, y2)), y7), 
           cross(cross(cross(y8, y4), cross(y7, y3)), y2))
y6 = np.round(y6 * (1/y6[2]))
print('y6:', y6)

y5 = cross(cross(cross(cross(y4, y1), cross(y3, y2)), y8), 
           cross(cross(cross(y8, y4), cross(y7, y3)), y1))
y5 = np.round(y5 * (1/y5[2]))
print('y5:', y5)

#mobile
# left
x10 = cross(cross(cross(cross(x12, x11), cross(x16, x15)), x9), 
           cross(cross(cross(x9, x12), cross(x13, x16)), x11))
x10 = np.round(x10 * (1/x10[2]))
print('x10:', x10)

x14 = cross(cross(cross(cross(x12, x11), cross(x16, x15)), x13), 
           cross(cross(cross(x9, x12), cross(x13, x16)), x15))
x14 = np.round(x14 * (1/x14[2]))
print('x14:', x14)

# right
y13 = cross(cross(cross(cross(y12, y11), cross(y16, y15)), y14), 
           cross(cross(cross(y9, y12), cross(y11, y10)), y16))
y13 = np.round(y13 * (1/y13[2]))
print('y13:', y13)

# Toy
# left
x18 = cross(cross(cross(cross(x17, x20), cross(x21, x24)), x19), 
           cross(cross(cross(x24, x23), cross(x20, x19)), x17))
x18 = np.round(x18 * (1/x18[2]))
print('x18:', x18)

x22 = cross(cross(cross(cross(x17, x20), cross(x21, x24)), x23), 
           cross(cross(cross(x24, x23), cross(x20, x19)), x21))
x22 = np.round(x22 * (1/x22[2]))
print('x22:', x22)

# right
y18 = cross(cross(cross(cross(y17, y20), cross(y21, y24)), y19), 
           cross(cross(cross(y24, y23), cross(y20, y19)), y17))
y18 = np.round(y18 * (1/y18[2]))
print('y18:', y18)

y22 = cross(cross(cross(cross(y17, y20), cross(y21, y24)), y23), 
           cross(cross(cross(y24, y23), cross(y20, y19)), y21))
y22 = np.round(y22 * (1/y22[2]))
print('y22:', y22)

# Naravno, ovde je samo gruba procena. Najbolje bi bilo praviti
# preseke vise od dve paralelne prave, tacnije svih koje znamo (vidimo).

x6: [501. 275.   1.]
y6: [564. 274.   1.]
y5: [396. 275.   1.]
x10: [691. 302.   1.]
x14: [694. 542.   1.]
y13: [295. 531.   1.]
x18: [359. 469.   1.]
x22: [357. 649.   1.]
y18: [492. 453.   1.]
y22: [493. 616.   1.]


In [205]:
xx = np.array([x17, x20, x24, x21, x12, x11, x15, x16])
yy = np.array([y17, y20, y24, y21, y12, y11, y15, y16])

# Ovo je osam tacaka na osnovu kojih odredjujemo F = FF. 
# Mogli smo uzeti i vise od 8 (teorijski i 7, ali onda je postupak nesto
# drugaciji.)

# Radi jednostavnosti nastavljamo bez normalizacije.

In [206]:
def jed(t2, t1):
    niz = np.array([t1[0]*t2[0], t1[0]*t2[1], t1[0]*t2[2],
                    t1[1]*t2[0], t1[1]*t2[1], t1[1]*t2[2],
                    t1[2]*t2[0], t1[2]*t2[1], t1[2]*t2[2]])
    #print(niz)
    return niz

In [207]:
M = np.zeros(9, dtype=int)
for i in range(8):
    M = np.vstack((M,jed(xx[i], yy[i])))
    
M = M[1:, :]   
print(M)
# Ovo je matrica formata 8x9 koja predstavlja 8 jednacina 
# dobijenih iz korespodencija.

[[ 11011  76109    121  49959 345321    549     91    629      1]
 [320142 358156    458 544521 609178    779    699    782      1]
 [320395 455007    461 678320 963312    976    695    987      1]
 [ 11811 104648    127  67053 594104    721     93    824      1]
 [ 72774  95472    234 117558 154224    378    311    408      1]
 [530278 250390    686 309973 146365    401    773    365      1]
 [526080 421275    685 492288 394215    641    768    615      1]
 [ 76685 164395    245 192495 412665    615    313    671      1]]


In [208]:
def DLT(matrica):
        u, s, v = np.linalg.svd(matrica, full_matrices=True)
        
        return v.T[:,-1]

In [209]:
FF = DLT(M)
FF = FF.reshape(3,3)
print(FF)
# Od V vektora SVD dekompozicije DLT algoritma uzmamo poslednju kolonu
# koja nam predstavlja FF matricu i [f11, f121, .. f33]

[[ 1.90962479e-05  2.40808449e-05  9.24161809e-03]
 [ 8.13301406e-05  1.56528885e-05 -7.58368863e-01]
 [ 2.74697222e-02  6.37651821e-01  1.32048563e-01]]


In [210]:
def test(FF, xx, yy):
    for i in range(8):
        rez = yy[i].dot(FF.dot(xx[i]))
        #print(rez)
        if (not (abs(rez) < 9.0e-12)):
            print(yy[i], xx[i], 'nije ni bliska nuli')
            return;
    print('Test prosao! Svi su blizu nule.')
    
test(FF, xx, yy)

print('det_f:', np.linalg.det(FF))
# proveravamo je li determinanta bliska nuli

Test prosao! Svi su blizu nule.
det_f: 9.207897352452107e-06


In [211]:
u, DD, v = np.linalg.svd(FF, full_matrices=True)
print('u:', u)
print()
print('DD:', DD)
print()
print('v:', v)

e1 = v[-1]
print('e1', e1)
# Treca kolona matrice v je trazeni epipol. Ta treca kolona odgovara
# najmanjoj sopstvenoj vrednosti matrice.

u: [[-1.09121376e-02  5.40747042e-03 -9.99925840e-01]
 [ 8.94512061e-01 -4.46877901e-01 -1.21784209e-02]
 [-4.46910615e-01 -8.94578616e-01  3.93456226e-05]]

DD: [7.90717916e-01 6.12180674e-01 1.90221357e-05]

v: [[-1.54340350e-02 -3.60380893e-01 -9.32677545e-01]
 [-4.02006605e-02 -9.31810775e-01  3.60711222e-01]
 [-9.99072419e-01  4.30614830e-02 -1.05949767e-04]]
e1 [-9.99072419e-01  4.30614830e-02 -1.05949767e-04]


In [212]:
e1 = e1 * (1/e1[2])
print(e1)

# Afine koordinate epipola e1.

[ 9.42968021e+03 -4.06433014e+02  1.00000000e+00]


In [213]:
e2 = u[:,-1]
print(e2)

# Da bi nasli e2 treba da resimo F.te2=0. Medjutim, primetimo da je
# Ft = UDV = (UDV.t).t = VDU.t. Ako je (U,D,V) SVD dekompozicija od F
# onda je (V,D,U) SVD dekompozicija od F.t. Zato je e2 treca kolona od U

e2 = e2 * (1/e2[2])
print('e2', e2)

# Afina koordinata epipola e2.

[-9.99925840e-01 -1.21784209e-02  3.93456226e-05]
e2 [-2.54139031e+04 -3.09524162e+02  1.00000000e+00]


In [214]:
DD1 = np.diag(DD).dot(np.diag([1,1,0]))
print('DD1:', DD1)

FF1 = u.dot(DD1.dot(v))
print('FF1:', FF1)
print('FF:', FF)

DD1: [[0.79071792 0.         0.        ]
 [0.         0.61218067 0.        ]
 [0.         0.         0.        ]]
FF1: [[ 9.31662102e-08  2.48999055e-05  9.24161607e-03]
 [ 8.10986959e-05  1.56628642e-05 -7.58368863e-01]
 [ 2.74697229e-02  6.37651821e-01  1.32048563e-01]]
FF: [[ 1.90962479e-05  2.40808449e-05  9.24161809e-03]
 [ 8.13301406e-05  1.56528885e-05 -7.58368863e-01]
 [ 2.74697222e-02  6.37651821e-01  1.32048563e-01]]


In [215]:
print('|FF|:', np.linalg.det(FF))
print('|FF1|:', np.linalg.det(FF1)) # FIXME: mozda je problematicno sto je ista kao FF1 kod prof

# Primetimo da imaju iste U i V u SVD dekompoziciji. Zato imaju 
# i iste epipolove.

|FF|: 9.207897352452107e-06
|FF1|: -3.7363584715077664e-21


In [216]:
# Triangulacija
T1 = np.identity(3)
T1 = np.vstack((T1, np.zeros(3)))
T1 = T1.T
print(T1)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [217]:
def vec(niz):
    p1, p2, p3 = niz
    m = np.array([[0, -p3, p2],
                  [p3, 0, -p1],
                  [-p2, p1, 0]])
    return m

#Matrica vektorskog mnozenja, kao kod rodrigeza

In [218]:
E2 = vec(e2)
E2

array([[ 0.00000000e+00, -1.00000000e+00, -3.09524162e+02],
       [ 1.00000000e+00,  0.00000000e+00,  2.54139031e+04],
       [ 3.09524162e+02, -2.54139031e+04,  0.00000000e+00]])

In [219]:
T2 = E2.dot(FF1)
print('E2.FF1:', T2)
print('e2:', e2)
T2 = np.hstack((T2, e2.reshape(3,1)))
print('T2:', T2)

# Za svaku tacku dobijamo sistem od 4 jednacine, mogli bi uzeti
# i samo 3 jednacine.

E2.FF1: [[-8.50262407e+00 -1.97368661e+02 -4.01138518e+01]
 [ 6.98112877e+02  1.62052216e+04  3.35587861e+03]
 [-2.06100556e+00 -3.90347389e-01  1.92759733e+04]]
e2: [-2.54139031e+04 -3.09524162e+02  1.00000000e+00]
T2: [[-8.50262407e+00 -1.97368661e+02 -4.01138518e+01 -2.54139031e+04]
 [ 6.98112877e+02  1.62052216e+04  3.35587861e+03 -3.09524162e+02]
 [-2.06100556e+00 -3.90347389e-01  1.92759733e+04  1.00000000e+00]]


In [220]:
def jednacine(x, y, T1, T2):
    return np.array([x[1]*T1[2] - x[2]*T1[1],
                    -x[0]*T1[2] + x[2]*T1[0],
                     y[1]*T2[2] - y[2]*T2[1],
                    -y[0]*T2[2] + y[2]*T2[0]])

In [221]:
def uAfine(xx):
    xx = xx * 1/xx[3]
    return xx[:-1]

In [222]:
# Iz tih jednacina, koje zavise od leve i desne projekcije tacke,
# se rekonstruise odgovarajuca tacka prostora. Naravno, koristimo
# u funkciji 'jednacine' matrice kamera T1 i T2. Evo kako izgleda na 
# primeru prve tacke.

t = jednacine(x1, y1, T1, T2)
print(t)

u, d, v = np.linalg.svd(t)
print('u:', u)
print('d:', d)
print('v:\n', v.T)

[[ 0.00000000e+00 -1.00000000e+00  7.40000000e+01  0.00000000e+00]
 [ 1.00000000e+00  0.00000000e+00 -3.32000000e+02  0.00000000e+00]
 [-8.52688294e+02 -1.62344977e+04  1.44234212e+06  3.84524162e+02]
 [ 7.99411556e+02 -4.43524845e+01 -7.55622164e+06 -2.58059031e+04]]
u: [[ 9.61951822e-06  6.03024174e-05 -3.64802809e-02 -9.99334371e-01]
 [-4.31576270e-05 -1.26851979e-05 -9.99334372e-01  3.64802798e-02]
 [ 1.87495099e-01  9.82265536e-01 -1.83117641e-05  6.17457170e-05]
 [-9.82265537e-01  1.87495100e-01  4.00549646e-05  3.96534109e-07]]
d: [7.69269085e+06 1.65810265e+04 1.44879498e+00 2.10569094e-02]
v:
 [[-1.22858095e-04 -4.14739454e-02 -6.56890558e-01 -7.52844401e-01]
 [-3.90022541e-04 -9.62238586e-01  2.29146318e-01 -1.46930991e-01]
 [ 9.99994457e-01  5.08613426e-04  2.38234959e-03 -2.26991736e-03]
 [ 3.30448034e-03 -2.69028913e-01 -7.18318233e-01  6.41585099e-01]]


In [223]:
p = v[3]
print(p)
s1 = uAfine(p)
print(s1)

slika1 = np.array([x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,
                   x14,x15,x16,x17,x18,x19,x20,x21,x22,x23,x24])
slika2 = np.array([y1,y2,y3,y4,y5,y6,y7,y8,y9,y10,y11,y12,y13,
                   y14,y15,y16,y17,y18,y19,y20,y21,y22,y23,y24])

rekonstruisane = np.array([0, 0, 0], dtype = int)

for i in range(24):
    u, d, v = np.linalg.svd(jednacine(slika1[i], slika2[i], T1, T2))
    rekonstruisane = np.vstack((rekonstruisane, uAfine(v[3])))
    
rekonstruisane

[-0.7528444  -0.14693099 -0.00226992  0.6415851 ]
[-1.17341316 -0.22901247 -0.00353798]


array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-1.17341316e+00, -2.29012474e-01, -3.53798328e-03],
       [-1.26366083e+00, -1.28991606e-01, -2.52803975e-03],
       [-1.85023219e+00, -4.44276262e-01, -2.57858573e-03],
       [-2.05557210e+00, -7.25471413e-01, -3.82711241e-03],
       [-1.14596379e+00, -1.01089968e+00, -3.49679697e-03],
       [-1.26430017e+00, -6.83424568e-01, -2.52512356e-03],
       [-1.83863462e+00, -1.06348026e+00, -2.57462059e-03],
       [-2.02719968e+00, -1.64213405e+00, -3.77043640e-03],
       [-1.26040518e+00, -1.64993534e+00, -4.86635342e-03],
       [-1.42080731e+00, -6.42312013e-01, -2.05323647e-03],
       [-1.66953234e+00, -8.18905316e-01, -2.15556706e-03],
       [-1.81118141e+00, -2.38649206e+00, -5.82025759e-03],
       [-1.22287097e+00, -2.68997411e+00, -4.61110838e-03],
       [-1.42499390e+00, -1.12351253e+00, -2.05141498e-03],
       [-1.66330473e+00, -1.35999584e+00, -2.16056080e-03],
       [-1.73386399e+00, -3.72548136e+00

In [229]:
rekonstrusane = rekonstruisane[1:,:]
i = 0
for x in rekonstrusane:
    print('x', i+1, ' = ', np.round(x*(1/x[2])))
    if (i % 4 == 3):
        print()
    i = i+1

x 1  =  [332.  65.   1.]
x 2  =  [500.  51.   1.]
x 3  =  [718. 172.   1.]
x 4  =  [537. 190.   1.]

x 5  =  [328. 289.   1.]
x 6  =  [501. 271.   1.]
x 7  =  [714. 413.   1.]
x 8  =  [538. 436.   1.]

x 9  =  [259. 339.   1.]
x 10  =  [692. 313.   1.]
x 11  =  [775. 380.   1.]
x 12  =  [311. 410.   1.]

x 13  =  [265. 583.   1.]
x 14  =  [695. 548.   1.]
x 15  =  [770. 629.   1.]
x 16  =  [313. 673.   1.]

x 17  =  [ 91. 629.   1.]
x 18  =  [360. 481.   1.]
x 19  =  [927. 615.   1.]
x 20  =  [700. 791.   1.]

x 21  =  [ 93. 824.   1.]
x 22  =  [358. 659.   1.]
x 23  =  [920. 802.   1.]
x 24  =  [696. 996.   1.]

