In [1]:
import numpy as np

In [2]:
x1 = np.array([958, 38, 1])
y1 = np.array([933, 33, 1])
x2 = np.array([1117, 111, 1])
y2 = np.array([1027, 132, 1])

x3 = np.array([874, 285, 1])
y3 = np.array([692, 223, 1])
x4 = np.array([707, 218, 1])
y4 = np.array([595, 123, 1])

x9 = np.array([292, 569, 1])
y9 = np.array([272, 360, 1])
x10 = np.array([770, 969, 1])
y10 = np.array([432, 814, 1])

x11 = np.array([770, 1465, 1])
y11 = np.array([414, 1284, 1])
x12 = np.array([317, 1057, 1])
y12 = np.array([258, 818, 1])
# Ovo je osam tacaka na osnovu kojih odredjujemo F = FF. 
# Mogli smo uzeti i vise od 8 (teorijski i 7, ali onda je postupak nesto
# drugaciji.)

In [3]:
xx = np.array([x1, x2, x3, x4, x9, x10, x11, x12])
yy = np.array([y1, y2, y3, y4, y9, y10, y11, y12])
# Ovo su vektori koji sadrze sve tacke.
# Radi jednostavnosti nastavljamo bez normalizacije.

In [4]:
def jed(t2, t1):
    niz = np.array([t1[0]*t2[0], t1[0]*t2[1], t1[0]*t2[2],
                    t1[1]*t2[0], t1[1]*t2[1], t1[1]*t2[2],
                    t1[2]*t2[0], t1[2]*t2[1], t1[2]*t2[2]])
    #print(niz)
    return niz

In [5]:
M = np.zeros(9, dtype=int)
for i in range(8):
    M = np.vstack((M,jed(xx[i], yy[i])))
    
M = M[1:, :]   
print(M)
# Ovo je matrica formata 8x9 koja predstavlja 8 jednacina 
# dobijenih iz korespodencija.

[[ 893814   35454     933   31614    1254      33     958      38       1]
 [1147159  113997    1027  147444   14652     132    1117     111       1]
 [ 604808  197220     692  194902   63555     223     874     285       1]
 [ 420665  129710     595   86961   26814     123     707     218       1]
 [  79424  154768     272  105120  204840     360     292     569       1]
 [ 332640  418608     432  626780  788766     814     770     969       1]
 [ 318780  606510     414  988680 1881060    1284     770    1465       1]
 [  81786  272706     258  259306  864626     818     317    1057       1]]


In [6]:
def DLT(matrica):
        u, s, v = np.linalg.svd(matrica, full_matrices=True)
        
        return v.T[:,-1]

In [7]:
FF = DLT(M)
FF = FF.reshape(3,3)
print(FF)
# Od V vektora SVD dekompozicije DLT algoritma uzmamo poslednju kolonu
# koja nam predstavlja FF matricu i [f11, f121, .. f33]

[[ 4.54020258e-07 -7.42529108e-07 -1.86611244e-03]
 [-1.99099442e-07  2.11775653e-07  2.77795603e-03]
 [ 3.96239362e-04 -2.72717967e-03  9.99990603e-01]]


In [8]:
def test(FF, xx, yy):
    for i in range(8):
        print('_____________')
        rez = yy[i].dot(FF.dot(xx[i]))
        print(rez)
        if (not (abs(rez) < 9.0e-10)):
            print(yy[i], xx[i], 'nije ni bliska nuli')
            return;
    print('Test prosao!')
    
test(FF, xx, yy)
# Pokrecemo test koji ne radi

print('det_f:', np.linalg.det(FF))
# proveravamo je li determinanta bliska nuli

_____________
-2.220446049250313e-16
_____________
-1.3389289676979388e-13
_____________
-2.8310687127941492e-14
_____________
-3.008704396734174e-14
_____________
3.297362383136715e-14
_____________
1.5876189252139739e-13
_____________
2.9620750296999176e-13
_____________
1.092459456231154e-13
Test prosao!
det_f: 1.7139674179610817e-12


In [9]:
u, DD, v = np.linalg.svd(FF, full_matrices=True)
print('u:', u)
print()
print('DD:', DD)
print()
print('v:', v)

e1 = v[-1]
print('e1', e1)
# Treca kolona matrice v je trazeni epipol. Ta treca kolona odgovara
# najmanjoj sopstvenoj vrednosti matrice.

#FIXME: zasto ovde nije dobar znak? Proveriti..

u: [[ 1.86610315e-03  6.01930967e-01 -7.98545947e-01]
 [-2.77794482e-03 -7.98541135e-01 -6.01933832e-01]
 [-9.99994400e-01  3.34158720e-03  1.81970886e-04]]

DD: [1.00000000e+00 9.88646915e-06 1.73364969e-07]

v: [[-3.96235743e-04  2.72716243e-03 -9.99996203e-01]
 [ 1.77651525e-01 -9.84089605e-01 -2.75417454e-03]
 [-9.84093379e-01 -1.77651942e-01 -9.45530903e-05]]
e1 [-9.84093379e-01 -1.77651942e-01 -9.45530903e-05]


In [10]:
e1 = e1 * (1/e1[2])
print(e1)

# Afine koordinate epipola e1.

[1.04078394e+04 1.87885919e+03 1.00000000e+00]


In [11]:
e2 = u[:,-1]
print(e2)

# Da bi nasli e2 treba da resimo F.te2=0. Medjutim, primetimo da je
# Ft = UDV = (UDV.t).t = VDU.t. Ako je (U,D,V) SVD dekompozicija od F
# onda je (V,D,U) SVD dekompozicija od F.t. Zato je e2 treca kolona od U

e2 = e2 * (1/e2[2])
print('e2', e2)

# Afina koordinata epipola e2.

[-7.98545947e-01 -6.01933832e-01  1.81970886e-04]
e2 [-4.38831707e+03 -3.30785789e+03  1.00000000e+00]


In [12]:
DD1 = np.diag(DD).dot(np.diag([1,1,0]))
print('DD1:', DD1)

FF1 = u.dot(DD1.dot(v))
print('FF1:', FF1)
print('FF:', FF)

DD1: [[1.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 9.88646915e-06 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]]
FF1: [[ 3.17782475e-07 -7.67123224e-07 -1.86611245e-03]
 [-3.01793759e-07  1.93236919e-07  2.77795602e-03]
 [ 3.96239393e-04 -2.72717967e-03  9.99990603e-01]]
FF: [[ 4.54020258e-07 -7.42529108e-07 -1.86611244e-03]
 [-1.99099442e-07  2.11775653e-07  2.77795603e-03]
 [ 3.96239362e-04 -2.72717967e-03  9.99990603e-01]]


In [13]:
print('|FF|:', np.linalg.det(FF))
print('|FF1|:', np.linalg.det(FF1)) # FIXME: mozda je problematicno sto je ista kao FF1 kod prof

# Primetimo da imaju iste U i V u SVD dekompoziciji. Zato imaju 
# i iste epipolove.

|FF|: 1.7139674179610817e-12
|FF1|: -2.2661317565660434e-27


In [14]:
x6 = np.array([1094, 536, 1])
y6 = np.array([980, 535, 1])
x7 = np.array([862, 729, 1])
y7 = np.array([652, 638, 1])
x8 = np.array([710, 648, 1])
y8 = np.array([567, 532, 1])

x14 = np.array([1487, 598, 1])
y14 = np.array([1303, 700, 1])
x15 = np.array([1462, 1079, 1])
y15 = np.array([1257, 1165, 1])
y13 = np.array([1077, 269, 1])
# Odredjivanje nevidljivih tacaka projekcije. 
# Naravno, ovde je samo gruba procena. Najbolje bi bilo praviti
# preseke vise od dve paralelne prave, tacnije svih koje znamo (vidimo).

In [123]:
def cross(x, y):
    z = np.cross(x, y)
    return z * (1/z[2])
    
    #vect = np.array([y, [0,0,0], [0,0,0]])
    #vect = np.array([[0, -y[2], y[1]],
    #                 [y[2], 0, -y[0]],
    #                 [-y[1], y[0], 0]])
    #return x.dot(vect)

x5 = cross(cross(cross(cross(x4, x8), cross(x6, x2)), x1), 
           cross(cross(cross(x1, x4), cross(x3, x2)), x8))
print(x5)
x5 = np.round(x5 * (1/x5[2]))
print(x5)

x13 = cross(cross(cross(cross(x9, x10), cross(x11, x12)), x14), 
           cross(cross(cross(x11, x15), cross(x10, x14)), x9))
x13 = np.round(x13 * (1/x13[2]))
print(x13)

x16 = cross(cross(cross(cross(x10, x14), cross(x11, x15)), x12), 
           cross(cross(cross(x9, x10), cross(x11, x12)), x15))
x16 = np.round(x16 * (1/x16[2]))
print(x16)

y5 = cross(cross(cross(cross(y4, y8), cross(y6, y2)), y1), 
           cross(cross(cross(y1, y4), cross(y3, y2)), y8))
y5 = np.round(y5 * (1/y5[2]))
print(y5)

y16 = cross(cross(cross(cross(y10, y14), cross(y11, y15)), y12), 
           cross(cross(cross(y9, y10), cross(y11, y12)), y15))
y16 = np.round(y16 * (1/y16[2]))
print(np.round(y16)) # kako je moguce da ovaj nije zaokruzen?!

[944.66875885 480.29978866   1.        ]
[945. 480.   1.]
[994. 242.   1.]
[995. 714.   1.]
[890. 440.   1.]
[1.067e+03 7.120e+02 1.000e+00]


In [124]:
# Triangulacija
T1 = np.identity(3)
T1 = np.vstack((T1, np.zeros(3)))
T1 = T1.T
print(T1)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [125]:
def vec(niz):
    p1, p2, p3 = niz
    m = np.array([[0, -p3, p2],
                  [p3, 0, -p1],
                  [-p2, p1, 0]])
    return m

#Matrica vektorskog mnozenja, kao kod rodrigeza

In [126]:
E2 = vec(e2)
E2

array([[ 0.00000000e+00, -1.00000000e+00, -3.30785789e+03],
       [ 1.00000000e+00,  0.00000000e+00,  4.38831707e+03],
       [ 3.30785789e+03, -4.38831707e+03,  0.00000000e+00]])

In [127]:
T2 = E2.dot(FF1)
print('E2.FF1:', T2)
print('e2:', e2)
T2 = np.hstack((T2, e2.reshape(3,1)))
print('T2:', T2)

# Za svaku tacku dobijamo sistem od 4 jednacine, mogli bi uzeti
# i samo 3 jednacine.

E2.FF1: [[-1.31070330e+00  9.02112258e+00 -3.30782958e+03]
 [ 1.73882441e+00 -1.19677298e+01  4.38827396e+03]
 [ 2.37554597e-03 -3.38551948e-03 -1.83633866e+01]]
e2: [-4.38831707e+03 -3.30785789e+03  1.00000000e+00]
T2: [[-1.31070330e+00  9.02112258e+00 -3.30782958e+03 -4.38831707e+03]
 [ 1.73882441e+00 -1.19677298e+01  4.38827396e+03 -3.30785789e+03]
 [ 2.37554597e-03 -3.38551948e-03 -1.83633866e+01  1.00000000e+00]]


In [156]:
def jednacine(x, y, T1, T2):
    return np.array([x[1]*T1[2] - x[2]*T1[1],
                    -x[0]*T1[2] + x[2]*T1[0],
                     y[1]*T2[2] - y[2]*T2[1],
                    -y[0]*T2[2] + y[2]*T2[0]])

In [157]:
def uAfine(xx):
    xx = xx * 1/xx[3]
    return xx[:-1]

In [160]:
# Iz tih jednacina, koje zavise od leve i desne projekcije tacke,
# se rekonstruise odgovarajuca tacka prostora. Naravno, koristimo
# u funkciji 'jednacine' matrice kamera T1 i T2. Evo kako izgleda na 
# primeru prve tacke.

t = jednacine(x1, y1, T1, T2)
print(t)

u, d, v = np.linalg.svd(t)
print('u:', u)
print('d:', d)
print('v:\n', v.T)

[[ 0.00000000e+00 -1.00000000e+00  3.80000000e+01  0.00000000e+00]
 [ 1.00000000e+00  0.00000000e+00 -9.58000000e+02  0.00000000e+00]
 [-1.66043139e+00  1.18560077e+01 -4.99426572e+03  3.34085789e+03]
 [-3.52708769e+00  1.21798123e+01  1.38252101e+04 -5.32131707e+03]]
u: [[-0.00219542 -0.01141793  0.23727863 -0.97137205]
 [ 0.05534849  0.28807879 -0.9278848  -0.23016722]
 [ 0.36943898 -0.89537502 -0.24359204 -0.04981297]
 [-0.92760259 -0.33938741 -0.15294303 -0.03127383]]
d: [1.59632182e+04 1.28531119e+03 4.98847967e+00 3.71509415e-02]
v:
 [[ 1.69994298e-04  2.31215349e-03  3.21270959e-03 -9.99992152e-01]
 [-4.33230845e-04 -1.14663517e-02 -9.99928919e-01 -3.23909226e-03]
 [-9.22275460e-01 -3.86501654e-01  4.83501792e-03 -1.03490733e-03]
 [ 3.86533000e-01 -9.22214535e-01  1.04143040e-02 -2.03315097e-03]]


In [151]:
p = v[3]
print(p)
s1 = uAfine(p)
print(s1)

slika1 = np.array([x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15,x16])
slika2 = np.array([y1,y2,y3,y4,y5,y6,y7,y8,y9,y10,y11,y12,y13,y14,y15,y16])

rekonstruisane = np.array([0, 0, 0], dtype = int)

for i in range(16):
    u, d, v = np.linalg.svd(jednacine(slika1[i], slika2[i], T1, T2))
    rekonstruisane = np.vstack((rekonstruisane, uAfine(v[3])))
    
rekonstruisane

[-0.99999215 -0.00323909 -0.00103491 -0.00203315]
[491.84353036   1.59313908   0.50901647]


array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [4.91843530e+02, 1.59313908e+00, 5.09016470e-01],
       [5.04614316e+02, 2.83555175e+01, 4.47171241e-01],
       [4.62901701e+02, 1.32736814e+02, 5.25575362e-01],
       [4.51538241e+02, 1.24865100e+02, 6.34769216e-01],
       [3.84165158e+02, 1.28745096e+02, 3.87166945e-01],
       [4.02597956e+02, 1.34081479e+02, 3.52730610e-01],
       [3.41967744e+02, 2.38664138e+02, 3.85483291e-01],
       [3.18681226e+02, 2.46478590e+02, 4.37378816e-01],
       [2.04982319e+02, 3.90574979e+02, 6.98659210e-01],
       [2.99381985e+02, 3.56356779e+02, 3.85907327e-01],
       [2.18131111e+02, 3.92907417e+02, 2.81440333e-01],
       [1.33994812e+02, 4.34968096e+02, 4.20089046e-01],
       [4.03900129e+02, 4.66971247e+01, 3.90915088e-01],
       [4.58570726e+02, 1.19093832e+02, 2.96527638e-01],
       [3.86631275e+02, 1.84150621e+02, 2.46041404e-01],
       [3.35312631e+02, 1.40080910e+02, 3.05685940e-01]])