In [167]:
import numpy as np

In [168]:
# Ovde su sve tacke cije su koordinate procitane sa slike.

# left
x1 = np.array([332, 74, 1])
x2 = np.array([500, 54, 1])
x3 = np.array([717, 165, 1])
x4 = np.array([537, 188, 1])
x5 = np.array([328, 293, 1])
x6 = np.array([])
x7 = np.array([713, 402, 1])
x8 = np.array([537, 429, 1])
x9 = np.array([259, 339, 1])
x10 = np.array([])
x11 = np.array([773, 365, 1])
x12 = np.array([311, 408, 1])
x13 = np.array([266, 591, 1])
x14 = np.array([])
x15 = np.array([768, 615, 1])
x16 = np.array([313, 671, 1])
x17 = np.array([91, 629, 1])
x18 = np.array([])
x19 = np.array([925, 599, 1])
x20 = np.array([699, 782, 1])
x21 = np.array([93, 824, 1])
x22 = np.array([])
x23 = np.array([918, 788, 1])
x24 = np.array([695, 987, 1])

# right
y1 = np.array([392, 75, 1])
y2 = np.array([563, 73, 1])
y3 = np.array([566, 197, 1])
y4 = np.array([370, 198, 1])
y5 = np.array([])
y6 = np.array([])
y7 = np.array([567, 424, 1])
y8 = np.array([375, 424, 1])
y9 = np.array([280, 312, 1])
y10 = np.array([714, 331, 1])
y11 = np.array([686, 401, 1])
y12 = np.array([234, 378, 1])
y13 = np.array([])
y14 = np.array([716, 555, 1])
y15 = np.array([685, 641, 1])
y16 = np.array([245, 615, 1])
y17 = np.array([121, 549, 1])
y18 = np.array([])
y19 = np.array([861, 652, 1])
y20 = np.array([458, 779, 1])
y21 = np.array([127, 721, 1])
y22 = np.array([])
y23 = np.array([858, 837, 1])
y24 = np.array([461, 976, 1])

In [169]:
# Odredjivanje nedostajucih tacaka.

def cross(x, y):
    z = np.cross(x, y)
    return z * (1/z[2])

# teeakane
# left
x6 = cross(cross(cross(cross(x4, x1), cross(x3, x2)), x7), 
           cross(cross(cross(x8, x4), cross(x7, x3)), x2))
x6 = np.round(x6 * (1/x6[2]))
print('x6:', x6)
# right
y6 = cross(cross(cross(cross(y4, y1), cross(y3, y2)), y7), 
           cross(cross(cross(y8, y4), cross(y7, y3)), y2))
y6 = np.round(y6 * (1/y6[2]))
print('y6:', y6)

y5 = cross(cross(cross(cross(y4, y1), cross(y3, y2)), y8), 
           cross(cross(cross(y8, y4), cross(y7, y3)), y1))
y5 = np.round(y5 * (1/y5[2]))
print('y5:', y5)

#mobile
# left
x10 = cross(cross(cross(cross(x12, x11), cross(x16, x15)), x9), 
           cross(cross(cross(x9, x12), cross(x13, x16)), x11))
x10 = np.round(x10 * (1/x10[2]))
print('x10:', x10)

x14 = cross(cross(cross(cross(x12, x11), cross(x16, x15)), x13), 
           cross(cross(cross(x9, x12), cross(x13, x16)), x15))
x14 = np.round(x14 * (1/x14[2]))
print('x14:', x14)

# right
y13 = cross(cross(cross(cross(y12, y11), cross(y16, y15)), y14), 
           cross(cross(cross(y9, y12), cross(y11, y10)), y16))
y13 = np.round(y13 * (1/y13[2]))
print('y13:', y13)

# Toy
# left
x18 = cross(cross(cross(cross(x17, x20), cross(x21, x24)), x19), 
           cross(cross(cross(x24, x23), cross(x20, x19)), x17))
x18 = np.round(x18 * (1/x18[2]))
print('x18:', x18)

x22 = cross(cross(cross(cross(x17, x20), cross(x21, x24)), x23), 
           cross(cross(cross(x24, x23), cross(x20, x19)), x21))
x22 = np.round(x22 * (1/x22[2]))
print('x22:', x22)

# right
y18 = cross(cross(cross(cross(y17, y20), cross(y21, y24)), y19), 
           cross(cross(cross(y24, y23), cross(y20, y19)), y17))
y18 = np.round(y18 * (1/y18[2]))
print('y18:', y18)

y22 = cross(cross(cross(cross(y17, y20), cross(y21, y24)), y23), 
           cross(cross(cross(y24, y23), cross(y20, y19)), y21))
y22 = np.round(y22 * (1/y22[2]))
print('y22:', y22)

# Naravno, ovde je samo gruba procena. Najbolje bi bilo praviti
# preseke vise od dve paralelne prave, tacnije svih koje znamo (vidimo).

x6: [501. 275.   1.]
y6: [564. 274.   1.]
y5: [396. 275.   1.]
x10: [691. 302.   1.]
x14: [694. 542.   1.]
y13: [295. 531.   1.]
x18: [359. 469.   1.]
x22: [357. 649.   1.]
y18: [492. 453.   1.]
y22: [493. 616.   1.]


In [170]:
xx = np.array([x1, x2, x3, x4, x12, x11, x15, x16])
yy = np.array([y1, y2, y3, y4, y12, y11, y15, y16])

# Ovo je osam tacaka na osnovu kojih odredjujemo F = FF. 
# Mogli smo uzeti i vise od 8 (teorijski i 7, ali onda je postupak nesto
# drugaciji.)

# Radi jednostavnosti nastavljamo bez normalizacije.

In [171]:
def jed(t2, t1):
    niz = np.array([t1[0]*t2[0], t1[0]*t2[1], t1[0]*t2[2],
                    t1[1]*t2[0], t1[1]*t2[1], t1[1]*t2[2],
                    t1[2]*t2[0], t1[2]*t2[1], t1[2]*t2[2]])
    #print(niz)
    return niz

In [172]:
M = np.zeros(9, dtype=int)
for i in range(8):
    M = np.vstack((M,jed(xx[i], yy[i])))
    
M = M[1:, :]   
print(M)
# Ovo je matrica formata 8x9 koja predstavlja 8 jednacina 
# dobijenih iz korespodencija.

[[130144  29008    392  24900   5550     75    332     74      1]
 [281500  30402    563  36500   3942     73    500     54      1]
 [405822  93390    566 141249  32505    197    717    165      1]
 [198690  69560    370 106326  37224    198    537    188      1]
 [ 72774  95472    234 117558 154224    378    311    408      1]
 [530278 250390    686 309973 146365    401    773    365      1]
 [526080 421275    685 492288 394215    641    768    615      1]
 [ 76685 164395    245 192495 412665    615    313    671      1]]


In [173]:
def DLT(matrica):
        u, s, v = np.linalg.svd(matrica, full_matrices=True)
        
        return v.T[:,-1]

In [174]:
FF = DLT(M)
FF = FF.reshape(3,3)
print(FF)
# Od V vektora SVD dekompozicije DLT algoritma uzmamo poslednju kolonu
# koja nam predstavlja FF matricu i [f11, f121, .. f33]

[[-1.31694465e-06 -9.38092613e-05  1.00509196e-02]
 [ 9.47391537e-05  1.52423224e-06 -4.18533932e-02]
 [-1.13034431e-02  3.34930615e-02  9.98447646e-01]]


In [178]:
def test(FF, xx, yy):
    for i in range(8):
        rez = yy[i].dot(FF.dot(xx[i]))
        #print(rez)
        if (not (abs(rez) < 9.0e-12)):
            print(yy[i], xx[i], 'nije ni bliska nuli')
            return;
    print('Test prosao! Svi su blizu nule.')
    
test(FF, xx, yy)

print('det_f:', np.linalg.det(FF))
# proveravamo je li determinanta bliska nuli

Test prosao! Svi su blizu nule.
det_f: -5.288681134203857e-09


In [180]:
u, DD, v = np.linalg.svd(FF, full_matrices=True)
print('u:', u)
print()
print('DD:', DD)
print()
print('v:', v)

e1 = v[-1]
print('e1', e1)
# Treca kolona matrice v je trazeni epipol. Ta treca kolona odgovara
# najmanjoj sopstvenoj vrednosti matrice.

u: [[-0.01004154  0.29240859 -0.95624076]
 [ 0.04182835 -0.95532912 -0.29256906]
 [-0.99907435 -0.04293582 -0.002638  ]]

DD: [9.99998845e-01 1.51998516e-03 3.47943347e-06]

v: [[ 0.01129697 -0.03346109 -0.99937617]
 [ 0.25949622 -0.9651007   0.03524683]
 [ 0.96567805  0.25973253  0.00221969]]
e1 [0.96567805 0.25973253 0.00221969]


In [181]:
e1 = e1 * (1/e1[2])
print(e1)

# Afine koordinate epipola e1.

[435.05165783 117.01318715   1.        ]


In [183]:
e2 = u[:,-1]
print(e2)

# Da bi nasli e2 treba da resimo F.te2=0. Medjutim, primetimo da je
# Ft = UDV = (UDV.t).t = VDU.t. Ako je (U,D,V) SVD dekompozicija od F
# onda je (V,D,U) SVD dekompozicija od F.t. Zato je e2 treca kolona od U

e2 = e2 * (1/e2[2])
print('e2', e2)

# Afina koordinata epipola e2.

[-0.95624076 -0.29256906 -0.002638  ]
e2 [362.48752136 110.90578679   1.        ]


In [185]:
DD1 = np.diag(DD).dot(np.diag([1,1,0]))
print('DD1:', DD1)

FF1 = u.dot(DD1.dot(v))
print('FF1:', FF1)
print('FF:', FF)

DD1: [[0.99999884 0.         0.        ]
 [0.         0.00151999 0.        ]
 [0.         0.         0.        ]]
FF1: [[ 1.89603625e-06 -9.29450854e-05  1.00509270e-02]
 [ 9.57221894e-05  1.78863335e-06 -4.18533909e-02]
 [-1.13034342e-02  3.34930639e-02  9.98447646e-01]]
FF: [[-1.31694465e-06 -9.38092613e-05  1.00509196e-02]
 [ 9.47391537e-05  1.52423224e-06 -4.18533932e-02]
 [-1.13034431e-02  3.34930615e-02  9.98447646e-01]]


In [186]:
print('|FF|:', np.linalg.det(FF))
print('|FF1|:', np.linalg.det(FF1)) # FIXME: mozda je problematicno sto je ista kao FF1 kod prof

# Primetimo da imaju iste U i V u SVD dekompoziciji. Zato imaju 
# i iste epipolove.

|FF|: -5.288681134203857e-09
|FF1|: 0.0


In [187]:
# Triangulacija
T1 = np.identity(3)
T1 = np.vstack((T1, np.zeros(3)))
T1 = T1.T
print(T1)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [188]:
def vec(niz):
    p1, p2, p3 = niz
    m = np.array([[0, -p3, p2],
                  [p3, 0, -p1],
                  [-p2, p1, 0]])
    return m

#Matrica vektorskog mnozenja, kao kod rodrigeza

In [190]:
E2 = vec(e2)
E2

array([[   0.        ,   -1.        ,  110.90578679],
       [   1.        ,    0.        , -362.48752136],
       [-110.90578679,  362.48752136,    0.        ]])

In [191]:
T2 = E2.dot(FF1)
print('E2.FF1:', T2)
print('e2:', e2)
T2 = np.hstack((T2, e2.reshape(3,1)))
print('T2:', T2)

# Za svaku tacku dobijamo sistem od 4 jednacine, mogli bi uzeti
# i samo 3 jednacine.

E2.FF1: [[-1.25371199e+00  3.71457281e+00  1.10775475e+02]
 [ 4.09735575e+00 -1.21409106e+01 -3.61914761e+02]
 [ 3.44878178e-02  1.09565051e-02 -1.62860379e+01]]
e2: [362.48752136 110.90578679   1.        ]
T2: [[-1.25371199e+00  3.71457281e+00  1.10775475e+02  3.62487521e+02]
 [ 4.09735575e+00 -1.21409106e+01 -3.61914761e+02  1.10905787e+02]
 [ 3.44878178e-02  1.09565051e-02 -1.62860379e+01  1.00000000e+00]]


In [192]:
def jednacine(x, y, T1, T2):
    return np.array([x[1]*T1[2] - x[2]*T1[1],
                    -x[0]*T1[2] + x[2]*T1[0],
                     y[1]*T2[2] - y[2]*T2[1],
                    -y[0]*T2[2] + y[2]*T2[0]])

In [193]:
def uAfine(xx):
    xx = xx * 1/xx[3]
    return xx[:-1]

In [194]:
# Iz tih jednacina, koje zavise od leve i desne projekcije tacke,
# se rekonstruise odgovarajuca tacka prostora. Naravno, koristimo
# u funkciji 'jednacine' matrice kamera T1 i T2. Evo kako izgleda na 
# primeru prve tacke.

t = jednacine(x1, y1, T1, T2)
print(t)

u, d, v = np.linalg.svd(t)
print('u:', u)
print('d:', d)
print('v:\n', v.T)

[[ 0.00000000e+00 -1.00000000e+00  7.40000000e+01  0.00000000e+00]
 [ 1.00000000e+00  0.00000000e+00 -3.32000000e+02  0.00000000e+00]
 [-1.51076941e+00  1.29626485e+01 -8.59538080e+02 -3.59057868e+01]
 [-1.47729366e+01 -5.80377189e-01  6.49490233e+03 -2.95124786e+01]]
u: [[ 0.01127972 -0.01379779 -0.82389209  0.56646643]
 [-0.05060639  0.02686675 -0.5664014  -0.8221354 ]
 [-0.13099729  0.99070696  0.00639144  0.03603573]
 [ 0.99002599  0.13261793 -0.01871971 -0.04371027]]
d: [6.56041750e+03 4.16440638e+01 1.01785229e+00 2.42444288e-01]
v:
 [[-2.20691609e-03 -8.23411299e-02 -2.94259069e-01 -9.52169453e-01]
 [-3.48139445e-04  3.06862836e-01  9.01512466e-01 -3.05139891e-01]
 [ 9.99990523e-01 -3.61801682e-03  8.50162344e-04 -2.26761271e-03]
 [-3.73673781e-03 -9.48178279e-01  3.17310813e-01 -1.60572963e-02]]


In [196]:
p = v[3]
print(p)
s1 = uAfine(p)
print(s1)

slika1 = np.array([x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,
                   x14,x15,x16,x17,x18,x19,x20,x21,x22,x23,x24])
slika2 = np.array([y1,y2,y3,y4,y5,y6,y7,y8,y9,y10,y11,y12,y13,
                   y14,y15,y16,y17,y18,y19,y20,y21,y22,y23,y24])

rekonstruisane = np.array([0, 0, 0], dtype = int)

for i in range(24):
    u, d, v = np.linalg.svd(jednacine(slika1[i], slika2[i], T1, T2))
    rekonstruisane = np.vstack((rekonstruisane, uAfine(v[3])))
    
rekonstruisane

[-0.4091128  -0.91222007 -0.0013658   0.02189506]
[-18.68516309 -41.66327915  -0.06237953]


array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 5.92982429e+01,  1.90031925e+01,  1.41220083e-01],
       [-6.50078990e+01, -1.30655326e+01, -1.26658982e-01],
       [-2.49593835e+01, -8.47004457e+00, -3.60152724e-02],
       [-3.05713661e+01, -1.41068472e+01, -6.92788966e-02],
       [-2.71315309e+01, -1.70143266e+01, -5.82496513e-02],
       [-4.00754220e+01, -1.60873255e+01, -7.18730236e-02],
       [-2.55169917e+01, -1.81407231e+01, -3.97580312e-02],
       [-2.50653974e+01, -2.50325613e+01, -5.66920537e-02],
       [-2.01249174e+01, -2.29669444e+01, -6.15462682e-02],
       [-3.26540292e+01, -1.37480645e+01, -4.68532227e-02],
       [-2.76335472e+01, -1.52525506e+01, -3.74709862e-02],
       [-2.33979165e+01, -3.16977426e+01, -7.90677910e-02],
       [-1.90379111e+01, -3.35847079e+01, -5.47592165e-02],
       [-2.76655438e+01, -1.95425135e+01, -3.78146347e-02],
       [-2.52770406e+01, -2.21076750e+01, -3.46179572e-02],
       [-1.86851631e+01, -4.16632791e+01

In [204]:
rekonstrusane = rekonstruisane[1:,:]
for x in rekonstrusane:
    print('x', np.round(x*(1/x[2])))

[420. 135.   1.]
[513. 103.   1.]
[693. 235.   1.]
[441. 204.   1.]
[466. 292.   1.]
[558. 224.   1.]
[642. 456.   1.]
[442. 442.   1.]
[327. 373.   1.]
[697. 293.   1.]
[737. 407.   1.]
[296. 401.   1.]
[348. 613.   1.]
[732. 517.   1.]
[730. 639.   1.]
[300. 668.   1.]
[133. 656.   1.]
[549. 450.   1.]
[884. 638.   1.]
[522. 835.   1.]
[145. 848.   1.]
[556. 645.   1.]
[879. 815.   1.]
[5.20e+02 1.03e+03 1.00e+00]
